// Comprehensive local registry of accredited public and private universities in Kenya
export const KENYAN_UNIVERSITIES = [
  "University of Nairobi (UoN)",
  "Jomo Kenyatta University of Agriculture and Technology (JKUAT)",
  "Kenyatta University (KU)",
  "Strathmore University",
  "United States International University-Africa (USIU-Africa)",
  "Egerton University",
  "Moi University",
  "Maseno University",
  "Technical University of Kenya (TUK)",
  "KCA University",
  "Daystar University",
  "Mount Kenya University (MKU)",
  "Catholic University of Eastern Africa (CUEA)",
  "Dedan Kimathi University of Technology (DeKUT)",
  "Multimedia University of Kenya (MMU)",
  "Masinde Muliro University of Science and Technology (MMUST)",
  "Cooperative University of Kenya",
  "Machakos University",
  "Technical University of Mombasa (TUM)",
  "Kisii University",
  "Karatina University",
  "Kabarak University",
  "Africa Nazarene University (ANU)",
  "Kirinyaga University",
  "Meru University of Science and Technology (MUST)",
  "Chuka University",
  "South Eastern Kenya University (SEKU)",
  "Murang'a University of Technology (MUT)",
  "Pwani University",
  "Laikipia University",
  "Kabianga University",
  "Maasai Mara University",
  "Taita Taveta University",
  "Rongo University",
  "Zetech University",
  "Management University of Africa (MUA)",
  "Riara University",
  "St. Paul's University",
  "Pan Africa Christian (PAC) University",
  "Adventist University of Africa"
];

// Common undergraduate university degree programs and course majors in Kenya
export const UNIVERSITY_COURSES = [
  "B.Sc. Computer Science",
  "B.Sc. Software Engineering",
  "B.Sc. Information Technology",
  "Bachelor of Commerce (B.Com)",
  "B.Sc. Actuarial Science",
  "Bachelor of Laws (LL.B)",
  "B.Sc. Civil Engineering",
  "B.Sc. Electrical & Electronic Engineering",
  "B.Sc. Mechanical Engineering",
  "B.Sc. Telecommunication Engineering",
  "Bachelor of Medicine and Bachelor of Surgery (MBChB)",
  "Bachelor of Pharmacy (B.Pharm)",
  "B.Sc. Nursing",
  "B.Sc. Economics",
  "B.Sc. Economics and Statistics",
  "B.Sc. Statistics",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Business Information Technology (BBIT)",
  "Bachelor of Procurement and Supply Chain Management",
  "Bachelor of Arts in Communication & Journalism",
  "Bachelor of Arts in International Relations",
  "Bachelor of Hospitality & Tourism Management",
  "Bachelor of Education (Arts)",
  "Bachelor of Education (Science)",
  "B.Sc. Environmental Science",
  "B.Sc. Agricultural Economics",
  "B.Sc. Biotechnology",
  "Bachelor of Arts in Psychology",
  "Bachelor of Arts in Sociology"
];
